_target_: flow_planning.models.transformer.DiffusionTransformer
obs_dim: ${obs_dim}
act_dim: ${act_dim}
d_model: 256
nhead: 4
num_layers: 2
T: ${experiment.T}
attn_dropout: 0.0
weight_decay: 1e-6
device: ${device}
